<a href="https://colab.research.google.com/github/aryac-2006/Countries-Dataset-/blob/main/Student_Performance_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Student_Performance_Dataset.csv to Student_Performance_Dataset.csv

In [3]:
filepath = "/content/Student_Performance_Dataset.csv"

In [20]:
df = pd.read_csv(filepath)

In [24]:
print("<<<<< Complete Dataset >>>>>\n")
df

<<<<< Complete Dataset >>>>>

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [17]:
print("<<<<< First five rows >>>>>:\n")
df.head()

<<<<< First five rows >>>>>:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
0,S0001,15,Male,12,1.0,65,Postgraduate,No,No,40,39,72,81,50.33,Average,Pass
1,S0002,19,Female,9,1.6,58,Graduate,No,Yes,80,44,35,47,53.00,Average,Pass
2,S0003,14,Female,12,3.6,64,High School,Yes,Yes,83,73,59,58,71.67,Good,Pass
3,S0004,18,Female,9,5.5,68,Postgraduate,Yes,No,68,48,77,54,64.33,Average,Pass
4,S0005,14,Male,10,5.0,80,High School,Yes,No,41,46,36,68,41.00,Poor,Fail

In [18]:
print("<<<<< Last five rows >>>>>:\n")
df.tail()

<<<<< Last five rows >>>>>:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
4995,S4996,17,Male,11,4.0,50,Graduate,No,No,64,60,70,93,64.67,Average,Pass
4996,S4997,19,Male,10,5.6,90,High School,Yes,No,44,59,43,63,48.67,Poor,Fail
4997,S4998,16,Female,9,2.3,61,Graduate,No,No,95,41,82,62,72.67,Good,Pass
4998,S4999,15,Male,11,2.9,82,Graduate,No,Yes,66,45,61,75,57.33,Average,Pass
4999,S5000,19,Female,10,2.0,97,Postgraduate,No,Yes,69,53,87,77,69.67,Good,Pass

In [25]:
print("Shape of Dataset:- ")
df.shape

Shape of Dataset:-

(5000, 16)

In [28]:
print("<<<<< COlumn Names >>>>>\n")
df.columns

<<<<< COlumn Names >>>>>

Index(['Student_ID', 'Age', 'Gender', 'Class', 'Study_Hours_Per_Day',
       'Attendance_Percentage', 'Parental_Education', 'Internet_Access',
       'Extracurricular_Activities', 'Math_Score', 'Science_Score',
       'English_Score', 'Previous_Year_Score', 'Final_Percentage',
       'Performance_Level', 'Pass_Fail'],
      dtype='object')

In [33]:
print("----Dataset Information----\n")
df.info()

----Dataset Information----

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  5000 non-null   object
 1   Age                         5000 non-null   int64
 2   Gender                      5000 non-null   object
 3   Class                       5000 non-null   int64
 4   Study_Hours_Per_Day         5000 non-null   float64
 5   Attendance_Percentage       5000 non-null   int64
 6   Parental_Education          5000 non-null   object
 7   Internet_Access             5000 non-null   object
 8   Extracurricular_Activities  5000 non-null   object
 9   Math_Score                  5000 non-null   int64
 10  Science_Score               5000 non-null   int64
 11  English_Score               5000 non-null   int64
 12  Previous_Year_Score         5000 non-null   int64
 13  Final_Percentage            5000 non-null   float64
 14  Performance_Level           5000 non-null   object
 15  Pass_Fail                   5000 non-null   object
dtypes: float64(2), int64(7), object(7)
memory usage: 625.1+ KB

In [37]:
print("Statistical Information:- \n")
df.describe()

Statistical Information:-

,Age,Class,Study_Hours_Per_Day,Attendance_Percentage,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,16.508800,10.496400,3.287260,74.919800,67.754800,66.895400,67.782800,67.282200,67.477656
std,1.718637,1.106812,1.587979,14.673842,18.724487,19.141195,19.248473,16.157511,10.964081
min,14.000000,9.000000,0.500000,50.000000,35.000000,35.000000,35.000000,40.000000,36.330000
25%,15.000000,10.000000,1.900000,62.000000,52.000000,50.000000,51.000000,53.000000,59.670000
50%,17.000000,10.000000,3.300000,75.000000,68.000000,67.000000,68.000000,67.000000,67.330000
75%,18.000000,11.000000,4.700000,88.000000,84.000000,83.000000,85.000000,81.000000,75.330000
max,19.000000,12.000000,6.000000,100.000000,100.000000,100.000000,100.000000,95.000000,98.330000

In [30]:
print("Data Types:\n")
df.dtypes

Data Types:

Student_ID                     object
Age                             int64
Gender                         object
Class                           int64
Study_Hours_Per_Day           float64
Attendance_Percentage           int64
Parental_Education             object
Internet_Access                object
Extracurricular_Activities     object
Math_Score                      int64
Science_Score                   int64
English_Score                   int64
Previous_Year_Score             int64
Final_Percentage              float64
Performance_Level              object
Pass_Fail                      object
dtype: object

In [38]:
print("Missing values:- \n")
df.isnull().sum()

Missing values:-

Student_ID                    0
Age                           0
Gender                        0
Class                         0
Study_Hours_Per_Day           0
Attendance_Percentage         0
Parental_Education            0
Internet_Access               0
Extracurricular_Activities    0
Math_Score                    0
Science_Score                 0
English_Score                 0
Previous_Year_Score           0
Final_Percentage              0
Performance_Level             0
Pass_Fail                     0
dtype: int64

In [39]:
print("Unique values in each column:- \n")
df.nunique()

Unique values in each column:-

Student_ID                    5000
Age                              6
Gender                           2
Class                            4
Study_Hours_Per_Day             56
Attendance_Percentage           51
Parental_Education               3
Internet_Access                  2
Extracurricular_Activities       2
Math_Score                      66
Science_Score                   66
English_Score                   66
Previous_Year_Score             56
Final_Percentage               181
Performance_Level                4
Pass_Fail                        2
dtype: int64

In [41]:
print("Sample of 5 random rows:")
df.sample(5)

Sample of 5 random rows:

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
1801,S1802,18,Male,10,2.1,53,Graduate,Yes,Yes,75,78,90,95,81.00,Excellent,Pass
3389,S3390,17,Male,11,5.4,73,Postgraduate,Yes,Yes,100,75,93,40,89.33,Excellent,Pass
289,S0290,14,Male,10,4.8,60,Postgraduate,No,No,38,51,71,85,53.33,Average,Pass
974,S0975,14,Female,10,3.0,74,Graduate,Yes,No,97,35,91,83,74.33,Good,Pass
4970,S4971,17,Female,9,4.2,88,High School,No,No,76,69,89,43,78.00,Good,Pass

In [43]:
print("Gender count:\n")
df['Gender'].value_counts()

Gender count:

Gender
Female    2553
Male      2447
Name: count, dtype: int64

In [46]:
print("Averange Final Percentage:-\n")
print(df["Final_Percentage"].mean())

Averange Final Percentage:-

67.47765600000001

In [47]:
print("Highest Final Percentage:-\n")
print(df["Final_Percentage"].max())

Highest Final Percentage:-

98.33

In [48]:
print("Lowest Final Percentage:-\n")
print(df["Final_Percentage"].min())

Lowest Final Percentage:-

36.33

In [75]:
print("Student with Final Percentage greater than 90 :-\n")
print(df[df["Final_Percentage"] > 90] [["Student_ID", "Gender", "Final_Percentage"]])

Student with Final Percentage greater than 90 :-

     Student_ID  Gender  Final_Percentage
21        S0022    Male             98.33
128       S0129  Female             90.67
144       S0145    Male             93.00
328       S0329  Female             91.33
405       S0406  Female             90.33
...         ...     ...               ...
4701      S4702    Male             93.00
4755      S4756    Male             92.33
4808      S4809  Female             95.33
4854      S4855    Male             93.67
4990      S4991  Female             93.67

[77 rows x 3 columns]

In [71]:
print("Count of Total no. of students failed :-")
print(df[df["Pass_Fail"] == "Fail"].shape[0])
print("---------------------------------------")

print("\nStudents Who Failed :-")
print(df[df["Pass_Fail"] == "Fail"] [["Student_ID", "Gender", "Pass_Fail"]])

Count of Total no. of students failed :-
265
---------------------------------------

Students Who Failed :-
     Student_ID  Gender Pass_Fail
4         S0005    Male      Fail
27        S0028    Male      Fail
82        S0083    Male      Fail
84        S0085  Female      Fail
97        S0098  Female      Fail
...         ...     ...       ...
4959      S4960  Female      Fail
4967      S4968  Female      Fail
4983      S4984    Male      Fail
4993      S4994    Male      Fail
4996      S4997    Male      Fail

[265 rows x 3 columns]

In [76]:
print("Top 10 student by Final Percentage :-\n")
df.sort_values(by = "Final_Percentage", ascending = False).head(10)

Top 10 student by Final Percentage :-

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
21,S0022,15,Male,12,2.8,83,Postgraduate,No,Yes,100,96,99,86,98.33,Excellent,Pass
3636,S3637,15,Female,9,3.8,90,High School,No,Yes,99,95,99,73,97.67,Excellent,Pass
3748,S3749,17,Male,11,0.5,60,Graduate,No,Yes,99,93,100,58,97.33,Excellent,Pass
2211,S2212,19,Male,11,1.8,87,Graduate,No,Yes,98,98,96,54,97.33,Excellent,Pass
1599,S1600,14,Male,9,5.0,83,High School,Yes,No,100,99,92,71,97.00,Excellent,Pass
4244,S4245,17,Female,12,1.3,57,Postgraduate,Yes,Yes,95,96,100,42,97.00,Excellent,Pass
2196,S2197,14,Female,11,1.7,72,High School,Yes,No,97,99,93,66,96.33,Excellent,Pass
4504,S4505,14,Female,11,1.1,59,Graduate,Yes,No,100,99,89,83,96.00,Excellent,Pass
1968,S1969,17,Male,12,5.4,54,High School,Yes,Yes,97,95,96,95,96.00,Excellent,Pass
3269,S3270,17,Female,9,5.2,88,Postgraduate,Yes,Yes,96,100,92,69,96.00,Excellent,Pass